name: Tagging Repo

on:
  push:
    branches:
      - test3

jobs:
  tagging:
    name: Tagging
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Tagging
        run: |
          CUR_TAG=$(git describe | cut -f 3 -d. | cut -f 1 -d-)
          TAG=$(( $CUR_TAG + 1 ))
          echo $TAG

